[platformio]
src_dir = ../../src

[env:bathroom-faucet-01]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    madhephaestus/ESP32Servo @ ^1.2.1
    bblanchon/ArduinoJson @ ^6.21.5
build_flags =
    -DWIFI_SSID='"Wokwi-GUEST"'
    -DWIFI_PASSWORD='""'
    -DSERVER_URL='"http://host.wokwi.internal:3000/api/data"'
    -DDEVICE_ID='"bathroom-faucet-01"'
